### ISSUE TITLE
Feature: Add types

### ISSUE THREAD

**Issue by SeanMcP** [SeanMcP/astro-emoji#1]
This package is an unbuilt Astro component. If I add types, I think it will cause non-TypeScript Astro projects to break on the unrecognized syntax.

Possibly there is a solution exporting two identical components: one with types and one without. I don't know if a) that will work, or b) there is a nice API for that pattern. Maybe something like:

```md
---
import Emoji from 'astro-emoji'
import { Typed as Emoji } from 'astro-emoji'
---
```

**Comment by MoustaphaDev** [comment]
One cannot opt out of TS in Astro projects AFAIK.
